### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by 8Kuula** [georgejs/nasdaq_stock#3]
Waited ~2mins, but nothing did happen. So I did ctrl+c out.

```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nasdaq_stock import nasdaq_stock as ns
>>> d = ns.stock('spyd')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dingleberry/.local/lib/python3.8/site-packages/nasdaq_stock/nasdaq_stock.py", line 28, in stock
    html_data = requests.get(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1821, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
KeyboardInterrupt
>>> 
```
Connection related, maybe.

**Comment by georgejs** [comment]
Hi Kasi,

I will look into it, I am the only owner of this package and it is not
actively maintained.

If the nasdaq website changed there url I will have to update it. However,
if it were to work you could just do "d.price" to get the price, but, yes I
understand that it just locked up. could be a firewall issue also but, let
me look at the code.

Regards,
-George

**Comment by 8Kuula** [comment]
Im trying to get stock information from Helsinki market. I was trying with this to do that, so even if it would work, would it do that?

**Comment by georgejs** [comment]
If the ticker exists in the nasdaq then yes. but, I designed the program to
hit the nasdaq site only. I suppose you could modify it to suit
whatever needs you have. It would require that you have a proper URL and
XPath, but at that point you are building a separate use case. I would
totally encourage you to build your own library, because it is a good idea
and I am sure others would benefit from it.

**Comment by 8Kuula** [comment]
I am not a good coder, and just stubled this. Just wished to get some stock data in conky.
Already tried to make crapy google search site scraping one to get OMXHPI data, but it is a mess. So started to search better option.
But no worries. I think of something or toss whole idea to trash :)

**Comment by georgejs** [comment]
Hey we all start somewhere. Let me see what I can do to help you.

**Comment by georgejs** [comment]
Updates completed. Nasdaq stocks is back up and running sorry it took so long.
Also, for anyone who cares to see what you can do with this program please see 
www.isaedge.com
